name: Robot Test CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
       
    - name: Start Django server
      run: |
        python manage.py runserver &

    - name: Wait for server to start
      run: |
        sleep 15

    - name: Chrome/Chromedriver Matcher Action
      uses: jamesmortensen/chromedriver-matcher-action@v1.0.1

    - name: Run Robot Framework tests
      run: |
        robot test.robot

    - name: Stop Django server
      run: |
        kill $(lsof -t -i:8000)
